# Generated by Django 6.0.3 on 2026-03-27 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Camara',
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.TextField()),
                ('id_frame', models.TextField()),
            ],
            options={
                'db_table': 'Camion',
            },
        ),
        migrations.CreateModel(
            name='Deteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_camara', models.ForeignKey(db_column='id_camara', on_delete=django.db.models.deletion.CASCADE, to='mapa.camara')),
                ('id_camion', models.ForeignKey(db_column='id_camion', on_delete=django.db.models.deletion.CASCADE, to='mapa.camion')),
            ],
            options={
                'verbose_name_plural': 'Detecciones',
                'db_table': 'Deteccion',
            },
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
